### ISSUE TITLE
Matching brackets

### ISSUE THREAD

**Issue by Superpat** [robertmeta/nofrils#1]
I feel like it could be a good idea if matching brackets were highlighted when your cursor is over them, as soon as I find what exactly allows that I'll try it out.

**Comment by robertmeta** [comment]
It does?  
![image](https://cloud.githubusercontent.com/assets/91007/10961609/7498de1e-835e-11e5-976a-279242537739.png)

![image](https://cloud.githubusercontent.com/assets/91007/10961624/b7d403fc-835e-11e5-9e81-51a0b959a5d5.png)

**Comment by Superpat** [comment]
I must of screwed something up then, since I dont get it in my solarized changes. I'll go check it out.

**Comment by robertmeta** [comment]
No problem, I have been changing stuff fast and furious, may well have fixed it after you forked.
