### ISSUE TITLE
Emacs version

### ISSUE THREAD

**Issue by lthms** [robertmeta/nofrils#16]
Hi all!

I am a happy user of no-frils for several months now, and I wanted to use this opportunity to thanks the author for making it opensource.

My workflow made emacs my primary editor though (especially because of Coq) and I saw that an emacs version of this theme was planed (in a reddit thread). I wanted to know what is its status and if there is anything I can do to help. I am currently using the tao theme of emacs, which is great but each time I fallback in vim for some reason, I remember I’d rather prefere nofrils.

Once again, thanks for sharing your theme!

**Comment by robertmeta** [comment]
Oh, my eyes where bigger than my stomach, once I started digging into the number of theme-able elements that people expect (https://github.com/bbatsov/zenburn-emacs/blob/master/zenburn-theme.el) I sort of panicked!  That said with the new go based generator that may flip around and become reasonable soon -- so stay tuned in the short term.

**Comment by lthms** [comment]
I am looking forward to it!

**Comment by lthms** [comment]
I’d tried for some time to get something I like and feels close to nofrils. I finally manage to get what I wanted by overriding the tao-yin theme. You can [read about it on my website](http://lthms.xyz/emacs.d#theme) and see an example here:

![My emacs theme](http://lthms.xyz/img/emacs.png)

**Comment by robertmeta** [comment]
Nice job!  Will check it out.

**Comment by lthms** [comment]
Just a heads-up, I am currently trying to create a dedicate theme (rather than modifying an existing one): [nordless-theme](https://github.com/lethom/nordless-theme.el).

**Comment by robertmeta** [comment]
That is awesome, will add it to readme.

**Comment by robertmeta** [comment]
I am not going to do this myself but added nordless-theme to the readme.
