### ISSUE TITLE
The VisualNOS group is unreadable

### ISSUE THREAD

**Issue by LemonBoy** [robertmeta/nofrils#17]
The light themes all end up as black on purple which is unreadable, at least on my monitor it is.
At the moment I'm using `hi! link VisualNOS Visual` as a workaround but I think someone out there may want to know when vim doesn't own the selection anymore.

**Comment by robertmeta** [comment]
Yep, I never use that, will fix -- make it close to normal highlight.

**Comment by robertmeta** [comment]
I tried just adding an underline to it when VisualNOS -- not sure if a great solution.
