### ISSUE TITLE
Cursor color over tags is unexpected in light theme

### ISSUE THREAD

**Issue by thatdevsherry** [robertmeta/nofrils#26]
This is the default cursor color when not over a tag
![screenshot from 2018-11-14 10-36-56](https://user-images.githubusercontent.com/40890226/48462291-6ad4bd00-e7f9-11e8-8e1f-9c650a73058c.png)

Moving the cursor over the opening tag character `<` makes the cursor color white and the closing tag character `>` becomes black.
![screenshot from 2018-11-14 10-36-59](https://user-images.githubusercontent.com/40890226/48462292-6ad4bd00-e7f9-11e8-91a7-47faa062825b.png)

Here the cursor is at the closing character `>`
![screenshot from 2018-11-14 10-37-01](https://user-images.githubusercontent.com/40890226/48462295-6b6d5380-e7f9-11e8-82ce-7906d4da736a.png)

I don't know if it's just me but my brain expects that if the cursor color was black, it should remain black. It makes me think the cursor is over the character where the cursor color is black when instead it's on the other character.

**Comment by moorereason** [comment]
I can't reproduce this from the terminal.  Are you using a plugin that's adding these tag boundary cues?

**Comment by robertmeta** [comment]
I too am having issues reproducing, can we get more info on terminal and such.

**Comment by thatdevsherry** [comment]
lol guys I haven't used the theme (or terminal vim) for so long now so I can't tell. I don't get why I didn't close this issue 😆 Since you guys can't reproduce it, we can assume it never appeared again 👍🏼
