### ISSUE TITLE
VSCode theme

### ISSUE THREAD

**Issue by 0x6a62** [robertmeta/nofrils#27]
FYI: I recently found a ported VSCode theme at https://github.com/urld/vscode-nofrills . I wanted to mention this in case you feel it is worth adding to your editor's list.  Note: This is not my repo, so I can't personally vouch for it, although at a first glance it's dark theme seems to work reasonably.

**Comment by moorereason** [comment]
But the extra `L`, though.  Why?! 🤦‍♂  :smile:

**Comment by robertmeta** [comment]
In readme now
