### ISSUE TITLE
Compatibility with latest neovim

### ISSUE THREAD

**Issue by edi9999** [robertmeta/nofrils#8]
It seems that nofrils doesn't clean syntax highlighting on "statements" (and on other highlight grouprs) since the latest version of neovim. 

I rather think it is a bug in neovim itself, but maybe someone else knows better

https://github.com/neovim/neovim/issues/4767

**Comment by robertmeta** [comment]
Appears to have been handled on the Neovim side a few days ago.

**Comment by edi9999** [comment]
Indeed !
