### ISSUE TITLE
Idea: documentation mode (invert code/comments)

### ISSUE THREAD

**Issue by joshgillies** [robertmeta/nofrils#9]
Something I've wondered recently is how well nofrils would fair if the code was muted and comments made more prominent. A theme like this would pair really well with a documentation first approach to coding. Thoughts?

**Comment by robertmeta** [comment]
Maybe, I have never met a developer who uses a "documentation first" approach.  But I already have a way to bold comments, muting the code wouldn't be hard, just not sure if it would be useful.

**Comment by joshgillies** [comment]
I'll take a look, but think being able to quickly switch between modes to focus on inline documentation could be quite handy.

**Comment by lthms** [comment]
I also believe being able to switch from one mode to another can be a great idea.

**Comment by robertmeta** [comment]
Yeah, I am going to implement this -- it is a question of -- is it gross for a plugin to have a function to call...

**Comment by robertmeta** [comment]
- :NofrilsFocusNormal reset back to normal settings
- :NofrilsFocusCode focus only code, fade everything else
- :NofrilsFocusComments focus only comments, fade everything else

**Comment by joshgillies** [comment]
Amazing work! Thanks for putting this in @robertmeta 👏
